"""empty message

Revision ID: 463b7a2a7bda
Revises: 
Create Date: 2018-10-21 22:17:11.433568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463b7a2a7bda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_location', sa.String(length=200), nullable=True),
    sa.Column('thumbnail_location', sa.String(length=200), nullable=True),
    sa.Column('has_food', sa.Float(), nullable=True),
    sa.Column('not_food', sa.Float(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('image')
    # ### end Alembic commands ###
